using System.Web.Mvc;

// DO NOT EDIT THIS FILE !!!!!!
// ----------------------------

namespace INF272SemesterTest2SectionB.Controllers
    {
    public class HomeController : Controller
        {
        public ActionResult Index()
            {
            return View();
            }
        }
    }

// DO NOT EDIT THIS FILE !!!!!!
// ----------------------------