using INF272SemesterTest2SectionB.Models;
using System.Web.Mvc;

// DO NOT EDIT THIS FILE !!!!!!
// ----------------------------

namespace INF272SemesterTest2SectionB.Controllers
    {
    public class Question01Controller : Controller
        {
        public ActionResult Question01()
            {
            return View(BookData.Authors);
            }
        }
    }

// DO NOT EDIT THIS FILE !!!!!!
// ----------------------------