using INF272SemesterTest2SectionB.Models;
using System.Collections.Generic;
using System.Web.Mvc;

// DO NOT EDIT THIS FILE !!!!!!
// ----------------------------

namespace INF272SemesterTest2SectionB.Controllers
    {
    public class Question02Controller : Controller
        {
        public ActionResult Question02()
            {
            List<Book> books = new List<Book>();
            foreach (Author author in BookData.Authors)
                {
                books.AddRange(author.Ratings);
                }
            BookTypeViewModel viewModel = new BookTypeViewModel
                {
                BookTypes = BookData.BookTypes,
                Books = books,
                };
            return View(viewModel);
            }
        }
    }

// DO NOT EDIT THIS FILE !!!!!!
// ----------------------------