using System.Collections.Generic;

// DO NOT EDIT THIS FILE !!!!!!
// ----------------------------

namespace INF272SemesterTest2SectionB.Models
    {
    public class Author
        {
        public int AuthorID { get; set; }
        public string AuthorLastName { get; set; }
        public string AuthorFirstName { get; set; }
        public List<Book> Ratings { get; set; }
        }
    }

// DO NOT EDIT THIS FILE !!!!!!
// ----------------------------