// DO NOT EDIT THIS FILE !!!!!!
// ----------------------------

namespace INF272SemesterTest2SectionB.Models
    {
    public class BookType
        {
        public int BookTypeID { get; set; }
        public string BookTypeDescription { get; set; }
        }
    }

// DO NOT EDIT THIS FILE !!!!!!
// ----------------------------