// DO NOT EDIT THIS FILE !!!!!!
// ----------------------------

namespace INF272SemesterTest2SectionB.Models
    {
    public class Book
        {
        public int BookID { get; set; }
        public int AuthorID { get; set; }
        public int BookTypeID { get; set; }
        public double Rating { get; set; }
        public string BookName { get; set; }
        }
    }

// DO NOT EDIT THIS FILE !!!!!!
// ----------------------------