using System.Collections.Generic;

// DO NOT EDIT THIS FILE !!!!!!
// ----------------------------

namespace INF272SemesterTest2SectionB.Models
    {
    public class BookTypeViewModel
        {
        public List<Book> Books { get; set; }
        public List<BookType> BookTypes { get; set; }
        }
    }

// DO NOT EDIT THIS FILE !!!!!!
// ----------------------------