using System.Collections.Generic;

// DO NOT EDIT THIS FILE !!!!!!
// ----------------------------

namespace INF272SemesterTest2SectionB.Models
    {
    public class RatingRangeViewModel
        {
        public List<Author> Authors { get; set; }
        public int Min { get; set; }
        }
    }

// DO NOT EDIT THIS FILE !!!!!!
// ----------------------------